### ISSUE TITLE
Record cut off at `=` sign

### ISSUE THREAD

**Issue by nsrderooy** [Pepijn98/mdr-cli#4]
When running dig;
`dig -t TXT example.com`

The following is returned;
```
example.com.		299	IN	TXT	"v=spf1 include:_spf.google.com include:amazonses.com -all"
```

when using mdr-cli the following is returned;
```
type  │ host │ address |
TXT   │ @    │ v       |
```

The same happens anywhere were a `=` sign is used in the address field.

**Comment by Pepijn98** [comment]
Sorry for the delay, this is fixed in 1.5.2
